var1 = hello                               #Here ,var1 is null
var2 = hello

all:
ifdef $(var1)
#    $(var1) = hello
    echo "hello world"
endif

#ifeq ($(var1) , $(var2))
#ifeq (var1 , var2)
#    echo "They are equal"
#else
#    echo "They are not equal"
#endif

.PHONY: all
